name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t my-app:test .
      
    - name: Run tests in Docker container
      run: |
        docker run my-app:test npm test
        
    - name: Run application for integration tests
      run: |
        docker run -d -p 3000:3000 my-app:test
        sleep 10  
        curl http://localhost:3000  
